/*
 * $$Id: BaseAuditoriaPK.java,v 1.2 2005/03/10 15:51:14 programa8 Exp $$
 * ===========================================================================
 * Material Propiedad SuperFerretería EPA C.A. 
 *
 * Creado por	: Superferretería EPA / Hibernate Synchronizer
 * Creado en 	: Wed Mar 02 14:08:23 GMT-04:00 2005
 * (C) Copyright SuperFerretería EPA C.A. Todos los Derechos Reservados
 * 
 * ---------------------------------------------------------------------------
 * Actualizaciones:
 * ---------------------------------------------------------------------------
 * $$Log: BaseAuditoriaPK.java,v $
 * $Revision 1.2  2005/03/10 15:51:14  programa8
 * $CR al 10/03/2005. Merging desde branch STABLE
 * $
 * $Revision 1.1.4.3  2005/03/07 13:55:31  programa8
 * $Integración Versiones Estable e Inestable al 07/03/2005
 * $
 * $Revision 1.1.6.3  2005/03/02 18:59:38  programa8
 * $Cambio en tabla Auditoria - idauditoria promovido a BIGINT
 * $
 * $Revision 1.1.4.2  2005/03/02 18:23:12  programa8
 * $Cambio en tabla Auditoria - idauditoria promovido a BIGINT
 * $$
 * ===========================================================================
 */

package com.becoblohm.cr.sincronizador.hibernate.base;

import java.io.Serializable;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class BaseAuditoriaPK implements Serializable {
	/** Log para este objeto. */
	protected static Log log = LogFactory.getLog(BaseAuditoriaPK.class);
	
	/** Value to indicate that hashCode needs to be regenerated */
	private int hashCode = Integer.MIN_VALUE;

	/** _idauditoria field */
	private java.lang.Long _idauditoria;
	/** _numcaja field */
	private java.lang.Short _numcaja;
	/** _numtienda field */
	private java.lang.Short _numtienda;

	/** 
	 * Constructor  
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public BaseAuditoriaPK () {
		super();
	}
	
	/** 
	  * Constructor  with parameters
	  *param	 _idauditoria an  java.lang.Long
	  *param	 _numcaja an  java.lang.Short
	  *param	 _numtienda an  java.lang.Short
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	*/
	public BaseAuditoriaPK (
		java.lang.Long _idauditoria,
		java.lang.Short _numcaja,
		java.lang.Short _numtienda) {

		this.setIdauditoria(_idauditoria);
		this.setNumcaja(_numcaja);
		this.setNumtienda(_numtienda);
	}


	/*
	 * Return the value associated with the ID column: idauditoria
	 * @return  java.lang.Long the idauditoria value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public java.lang.Long getIdauditoria () {
		return this._idauditoria;
	}

	/*
	 * Set the value of _idauditoria
	 * @param _idauditoria the java.lang.Long value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public void setIdauditoria (java.lang.Long _idauditoria) {
		hashCode = Integer.MIN_VALUE;
		this._idauditoria = _idauditoria;
	}

	/*
	 * Return the value associated with the ID column: numcaja
	 * @return  java.lang.Short the numcaja value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public java.lang.Short getNumcaja () {
		return this._numcaja;
	}

	/*
	 * Set the value of _numcaja
	 * @param _numcaja the java.lang.Short value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public void setNumcaja (java.lang.Short _numcaja) {
		hashCode = Integer.MIN_VALUE;
		this._numcaja = _numcaja;
	}

	/*
	 * Return the value associated with the ID column: numtienda
	 * @return  java.lang.Short the numtienda value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public java.lang.Short getNumtienda () {
		return this._numtienda;
	}

	/*
	 * Set the value of _numtienda
	 * @param _numtienda the java.lang.Short value
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public void setNumtienda (java.lang.Short _numtienda) {
		hashCode = Integer.MIN_VALUE;
		this._numtienda = _numtienda;
	}

	/** 
	 * @see java.lang.Object#equals(java.lang.Object)
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.becoblohm.cr.sincronizador.hibernate.AuditoriaPK)) return false;
			com.becoblohm.cr.sincronizador.hibernate.AuditoriaPK mObj = (com.becoblohm.cr.sincronizador.hibernate.AuditoriaPK) obj;
			if (null != this.getIdauditoria() && null != mObj.getIdauditoria()) {
				if (!this.getIdauditoria().equals(mObj.getIdauditoria())) {
					return false;
				}
			} else {
				return false;
			}

			if (null != this.getNumcaja() && null != mObj.getNumcaja()) {
				if (!this.getNumcaja().equals(mObj.getNumcaja())) {
					return false;
				}
			} else {
				return false;
			}

			if (null != this.getNumtienda() && null != mObj.getNumtienda()) {
				if (!this.getNumtienda().equals(mObj.getNumtienda())) {
					return false;
				}
			} else {
				return false;
			}

			return true;
	}

	/** 
	 * @see java.lang.Object#hashCode()
	  * @since Wed Mar 02 14:08:23 GMT-04:00 2005
	 */
	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdauditoria()) {
				sb.append(this.getIdauditoria().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getNumcaja()) {
				sb.append(this.getNumcaja().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getNumtienda()) {
				sb.append(this.getNumtienda().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}

}