/*
 * $$Id: _RootDAO.java,v 1.2 2005/03/10 15:50:32 programa8 Exp $$
 * ===========================================================================
 * Material Propiedad SuperFerretería EPA C.A. 
 *
 * Creado por	: Superferretería EPA / Hibernate Synchronizer
 * Creado en 	: Wed Dec 01 18:36:31 GMT-04:00 2004
 * (C) Copyright SuperFerretería EPA C.A. Todos los Derechos Reservados
 * 
 * ---------------------------------------------------------------------------
 * Actualizaciones:
 * ---------------------------------------------------------------------------
 * $$Log: _RootDAO.java,v $
 * $Revision 1.2  2005/03/10 15:50:32  programa8
 * $CR al 10/03/2005. Merging desde branch STABLE
 * $
 * $Revision 1.1.4.2  2005/03/07 12:53:55  programa8
 * $Integración Versiones Estable e Inestable al 07/03/2005
 * $
 * $Revision 1.1.6.2  2005/02/28 18:13:47  programa8
 * $Version Inestable al 28/02/2005
 * $    *-Preparación para trabajar sin administrador de ventanas.
 * $    *-Reordenamiento de GUI
 * $    *-Mejoras en scroll y pantallas de pagos
 * $    *- Mantenimiento de estado en Cliente en Espera
 * $    *- Avisos del sistema manejados por la aplicacion
 * $    *- Desbloqueo de caja por otros usuarios reparado.
 * $
 * $Revision 1.1.4.1  2005/01/04 18:23:01  acastillo
 * $Integracion CR EPA3 - Costa Rica
 * $
 * $Revision 1.1.8.1  2005/01/04 16:07:16  acastillo
 * $Integracion CR EPA3 - Costa Rica
 * $
 * $Revision 1.1.6.1  2004/12/17 16:09:25  acastillo
 * $Cambios Prueba EPA 3
 * $$
 * ===========================================================================
 */

package com.becoblohm.cr.sincronizador.hibernate.dao;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public abstract class _RootDAO extends com.becoblohm.cr.sincronizador.hibernate.base._BaseRootDAO {
	/** Log para este objeto. */
	private static Log log = LogFactory.getLog(_RootDAO.class);
	
	// your custom code here
}