/*
 * $$Id: ProdcodigoexternoDAO.java,v 1.2 2005/03/10 15:54:44 programa8 Exp $$
 * ===========================================================================
 * Material Propiedad SuperFerretería EPA C.A. 
 *
 * Creado por	: Superferretería EPA / Hibernate Synchronizer
 * Creado en 	: Tue Feb 15 08:03:32 GMT-04:00 2005
 * (C) Copyright SuperFerretería EPA C.A. Todos los Derechos Reservados
 * 
 * ---------------------------------------------------------------------------
 * Actualizaciones:
 * ---------------------------------------------------------------------------
 * $$Log: ProdcodigoexternoDAO.java,v $
 * $Revision 1.2  2005/03/10 15:54:44  programa8
 * $CR al 10/03/2005. Merging desde branch STABLE
 * $
 * $Revision 1.1.2.2  2005/03/07 12:53:28  programa8
 * $Integración Versiones Estable e Inestable al 07/03/2005
 * $
 * $Revision 1.1.4.1  2005/02/28 18:39:16  programa8
 * $Version Inestable al 28/02/2005
 * $    *-Preparación para trabajar sin administrador de ventanas.
 * $    *-Reordenamiento de GUI
 * $    *-Mejoras en scroll y pantallas de pagos
 * $    *- Mantenimiento de estado en Cliente en Espera
 * $    *- Avisos del sistema manejados por la aplicacion
 * $    *- Desbloqueo de caja por otros usuarios reparado.
 * $
 * $Revision 1.1.2.1  2005/02/15 17:43:39  acastillo
 * $Ajuste de estructura prodcodigoexterno
 * $$
 * ===========================================================================
 */

package com.becoblohm.cr.sincronizador.hibernate.dao;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.becoblohm.cr.sincronizador.hibernate.base.BaseProdcodigoexternoDAO;

/**
 * This is the object class that relates to the prodcodigoexterno table.
 * Any customizations belong here.
	  * @since Tue Feb 15 08:03:32 GMT-04:00 2005
 */
/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public class ProdcodigoexternoDAO extends BaseProdcodigoexternoDAO {
	/** Log para este objeto. */
	private static Log log = LogFactory.getLog(ProdcodigoexternoDAO.class);
	// your custom code here
}